### ISSUE TITLE
Nice Library, Is it Windows only?

### ISSUE THREAD

**Issue by damies13** [Atyors/robotframework-ImageRobot#2]
Hi,

Wanted to say this looks like a nice library, but have a question if you support all OS's that are supported by robot framework? or as a minimum Windows, Linux and MacOS?

From my memory of pygetwindow it currently only supports Windows OS, so you might want to update your documentation to reflect that to prevent confusion.

**Comment by Romathi** [comment]
Hello,

You are correct, the Focus object is Windows only. 
To be honest, I did this project a few years ago just for the sake of having fun developing some stuff. I did not ever try on anything other than Windows.

As you said, I add this in the documentation.

Thanks for you feedback.
